CREATE TABLE product (
id BIGINT NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
description VARCHAR(100) NOT NULL,
price VARCHAR(6) NOT NULL,
image LONGBLOB NOT NULL,
quantity VARCHAR(100) NOT NULL,
brand VARCHAR(100) NOT NULL,
category VARCHAR(100) NOT NULL,
state TINYINT(1) NOT NULL DEFAULT 1,
PRIMARY KEY (id)
);