CREATE TABLE user (
id BIGINT NOT NULL AUTO_INCREMENT,
name VARCHAR(100) NOT NULL,
lastName VARCHAR(100) NOT NULL,
usuario VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
phone VARCHAR(100) NOT NULL,
phone2 VARCHAR(100),
state TINYINT(1) NOT NULL DEFAULT 1,
PRIMARY KEY (id)
);